from django.conf.urls import patterns, include, url

urlpatterns = patterns('NGAS.views',
    url(r'^home/$', 'index'),
    url(r'^hosts/$', 'hostdirect'),
    url(r'^hosts/query/display/$', 'hostview'),
    url(r'^hosts/query/$', 'hostquery'),
    url(r'^hosts/query/(?P<option>\w+)/(\w+)/$', 'hosturl'),
    url(r'^hosts/details/(?P<host_id>\d+)/$', 'hostdetails'),
    url(r'^hosts/details/(?P<host_id>\w+)/$', 'hostdetails'),
    url(r'^disks/$', 'diskdirect'),
    url(r'^disks/query/$', 'diskquery'),
    url(r'^disks/query/history/$', 'diskhistquery'),
    url(r'^disks/query/status/$', 'diskstatusquery'),
    url(r'^disks/query/history/search/$', 'diskhistview'),
    url(r'^disks/query/status/search/(\w+)/$', 'diskstatsurl'),
    url(r'^disks/query/status/search/$', 'diskstatsview'),
    url(r'^disks/query/status/update/$', 'diskstatsupdate'),
    url(r'^disks/query/status/update/submit/$', 'diskstatssubmit'),
    url(r'^disks/query/display/', 'diskview'),
    url(r'^disks/query/(?P<option>\w+)/$', 'diskurl'),
    url(r'^disks/details/(?P<disk_id>\w+)/$', 'diskdetails'),
    url(r'^disks/details/(?P<disk_id>\w+)/history/$', 'diskhistory'),
    url(r'^disks/details/(?P<disk_id>\w+)/history/(?P<hist_id>\d+)/description/$', 'diskhistdesc'),
    url(r'^disks/details/(?P<disk_id>\w+)/(?P<option>\w+)/(?P<page>\w+)/$', 'fileview'),
    url(r'^files/$', 'filedirect'),
    url(r'^files/query/$', 'filequery'),
    url(r'^files/query/opt2/$', 'filedaterange', {'opt':2}),
    url(r'^files/query/opt3/$', 'filesearchform'),
    url(r'^files/query/opt4/$', 'filetotalstats'),
    url(r'^files/query/opt5/$', 'filestatcheck'),
    url(r'^files/query/opt6/$', 'filedaterange', {'opt':6}),
    url(r'^files/query/opt7/$', 'filediskcheck'),
    url(r'^files/query/insstat/display/$', 'filerangedisp'),                   
    url(r'^files/query/display/', 'fileview'),
    url(r'^files/query/opt5/results/$', 'filestatres'),
    url(r'^files/query/opt7/results/$', 'filediskres'),
    url(r'^files/query/opt5/results/(?P<disk_id>\w+)/(?P<status>\w+)/$', 'filestatdisk'),
    url(r'^files/query/(?P<option>\w+)/(\w+)/$', 'fileurl'),
    url(r'^files/details/(?P<file_id>\d+)/$', 'filedetails'),
)
